USE projeto;
INSERT INTO area_do_conhecimento (nome) VALUES ("Ciências Agrárias");
INSERT INTO area_do_conhecimento (nome) VALUES ("Ciências Biológicas");
INSERT INTO area_do_conhecimento (nome) VALUES ("Ciências da Saúde");
INSERT INTO area_do_conhecimento (nome) VALUES ("Ciências Exatas e da Terra");
INSERT INTO area_do_conhecimento (nome) VALUES ("Engenharias");
INSERT INTO area_do_conhecimento (nome) VALUES ("Ciências Humanas");
INSERT INTO area_do_conhecimento (nome) VALUES ("Ciências Sociais Aplicadas");
INSERT INTO area_do_conhecimento (nome) VALUES ("Linguistica, Letras e Artes");
INSERT INTO departamento (nome, acronimo) VALUES ("Departamento de Ciências Agrárias", "DCA");
INSERT INTO departamento (nome, acronimo) VALUES ("Departamento de Ciências Biológicas", "DCB");
INSERT INTO departamento (nome, acronimo) VALUES ("Departamento de Ciências da Saúde", "DCS");
INSERT INTO departamento (nome, acronimo) VALUES ("Departamento de Ciências Exatas e da Terra", "DCET");
INSERT INTO departamento (nome, acronimo) VALUES ("Departamento de Engenharias", "DE");
INSERT INTO departamento (nome, acronimo) VALUES ("Departamento de Ciências Humanas", "DCH");
INSERT INTO departamento (nome, acronimo) VALUES ("Departamento de Ciências Sociais Aplicadas", "DCSA");
INSERT INTO departamento (nome, acronimo) VALUES ("Departamento de Linguistica, Letras e Artes", "DLLA");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Mr. Marlin Ritchie DDS", "8", "8");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Roscoe Jenkins", "5", "5");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Addison Pouros", "3", "3");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Miss Cynthia Stanton", "3", "3");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Ray Spinka", "1", "1");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Reva Kovacek", "6", "6");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Mrs. Simone Rowe", "3", "3");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Alta Wolff", "2", "2");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Dr. Pauline Kemmer", "3", "3");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Mr. Austen Fay Sr.", "2", "2");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Marianne Weissnat IV", "7", "7");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Prof. Raven Paucek Jr.", "8", "8");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Leola Stokes", "7", "7");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Malika Harber I", "7", "7");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Prof. Deshawn Heller", "3", "3");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Giovani Bosco", "1", "1");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Prof. Bethel Torphy I", "5", "5");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Clovis Reichert DDS", "2", "2");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Chanel Kassulke", "2", "2");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Dax Ryan", "2", "2");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("May Koelpin DDS", "5", "5");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Modesta Kuhlman DDS", "2", "2");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Gerard Rutherford", "8", "8");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Layne Hintz", "3", "3");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Kacey Bergnaum", "2", "2");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Alison Gislason", "4", "4");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Dr. Jameson Dach III", "8", "8");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Anahi Koch III", "6", "6");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Nels Stiedemann", "7", "7");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Dixie Thompson III", "6", "6");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Frederik Champlin", "3", "3");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Britney Wiegand", "7", "7");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Josue O'Reilly", "5", "5");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Mrs. Eudora Roberts", "8", "8");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Lucius Schmidt", "7", "7");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Gia Labadie PhD", "6", "6");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Dax Murphy", "4", "4");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Abbey Medhurst", "5", "5");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Esmeralda Heathcote I", "2", "2");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Dr. Kendra Klocko DDS", "7", "7");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Maurine Satterfield", "2", "2");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Mr. Keanu Wuckert MD", "5", "5");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Meagan Hammes", "4", "4");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Prof. Carmine Parker", "7", "7");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Emely Grimes", "3", "3");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Rudolph Hilpert", "6", "6");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Elinor Rice", "8", "8");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Tyreek Stark", "7", "7");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Prof. Violette Hahn Jr.", "5", "5");
INSERT INTO avaliador (nome, departamento, area_do_conhecimento) VALUES ("Murphy Rath", "2", "2");