DROP DATABASE IF EXISTS Questao03;
CREATE DATABASE Questao03;
USE Questao03;
CREATE TABLE Hotel(
    CNPJ VARCHAR(14) UNIQUE NOT NULL PRIMARY KEY,
    Nome VARCHAR(300) NOT NULL,
    Data_fundacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Quarto(
    Id INT UNIQUE NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Numero INT NOT NULL,
    Camas INT NOT NULL,
    Hotel VARCHAR(14) NOT NULL,
    FOREIGN KEY (Hotel) REFERENCES Hotel(CNPJ)
);